import Link from "next/link"
import { ArrowRight, CircleDot, Mail, MapPinned, Pickaxe, ShieldCheck, Waves } from "lucide-react"

const video = process.env.NEXT_PUBLIC_MINING_VIDEO_URL || "https://videos.pexels.com/video-files/853870/853870-hd_1920_1080_30fps.mp4"

export default function Home() {
  return <main>
    <section className="relative min-h-[92vh] overflow-hidden border-b border-border">
      <video autoPlay muted loop playsInline poster="https://images.pexels.com/photos/162568/mining-excavator-excavator-bucket-162568.jpeg?auto=compress&cs=tinysrgb&w=1800" className="absolute inset-0 size-full object-cover opacity-45" aria-label="Mining operations footage"><source src={video} type="video/mp4" /></video>
      <div className="absolute inset-0 bg-[linear-gradient(90deg,#0b0f0e_10%,rgba(11,15,14,.86)_42%,rgba(11,15,14,.35)),linear-gradient(0deg,#0b0f0e_0%,transparent_50%)]" />
      <div className="relative mx-auto flex min-h-[92vh] max-w-7xl flex-col px-6 py-7 lg:px-10">
        <nav className="flex items-center justify-between"><Link href="/" className="flex items-center gap-3"><span className="grid size-9 place-items-center border border-primary/60 text-primary"><Pickaxe size={18}/></span><span className="font-mono text-sm tracking-[.25em]">MOKAMBO<span className="text-primary">//</span>OPS</span></Link><div className="hidden items-center gap-8 text-sm text-muted-foreground md:flex"><Link href="/portal" className="transition-colors hover:text-primary">Portal</Link><a href="#vision" className="transition-colors hover:text-primary">Our vision</a><a href="#contact" className="transition-colors hover:text-primary">Contact</a></div><Link href="/portal" className="flex items-center gap-2 border border-primary/60 px-4 py-2 text-sm text-primary transition-colors hover:bg-primary hover:text-primary-foreground">Open portal <ArrowRight size={15}/></Link></nav>
        <div className="flex flex-1 items-center py-24"><div className="max-w-3xl"><p className="mb-6 flex items-center gap-3 font-mono text-xs uppercase tracking-[.3em] text-primary"><CircleDot size={12} className="animate-pulse"/> Field intelligence / 01</p><h1 className="max-w-3xl text-balance text-5xl font-semibold leading-[1.02] tracking-[-.04em] md:text-7xl">Know what&apos;s beneath. <span className="text-primary">Move with certainty.</span></h1><p className="mt-8 max-w-xl text-lg leading-8 text-muted-foreground">Mokambo brings survey intelligence, site visibility, and the ground truth of your operation into one calm command surface.</p><div className="mt-10 flex flex-wrap gap-4"><Link href="/portal" className="flex items-center gap-3 bg-primary px-5 py-3 font-medium text-primary-foreground hover:bg-primary/90">Enter operations portal <ArrowRight size={17}/></Link><a href="#vision" className="flex items-center gap-3 border border-border bg-background/30 px-5 py-3 hover:border-primary/70">Our vision <Waves size={17}/></a></div></div></div>
        <div className="flex items-center gap-3 font-mono text-[10px] uppercase tracking-[.2em] text-muted-foreground"><span className="h-px w-12 bg-primary"/> Real work. Real ground. Responsible progress.</div>
      </div>
    </section>
    <section id="vision" className="ore-grid border-b border-border"><div className="mx-auto grid max-w-7xl gap-14 px-6 py-24 lg:grid-cols-[1.1fr_.9fr] lg:px-10"><div><p className="font-mono text-xs uppercase tracking-[.25em] text-primary">Our vision</p><h2 className="mt-5 max-w-2xl text-4xl font-semibold tracking-tight md:text-5xl">Make every decision closer to the ground truth.</h2><p className="mt-6 max-w-xl leading-8 text-muted-foreground">Mining is a coordination problem measured in rock, distance, and consequence. We build tools that make the invisible legible—so teams can work safer and plan smarter.</p></div><div className="grid gap-4 sm:grid-cols-3 lg:grid-cols-1"><Feature icon={<MapPinned/>} title="Traceable" text="Follow survey lines through depth and elevation."/><Feature icon={<ShieldCheck/>} title="Field-ready" text="A clear surface for people doing consequential work."/><Feature icon={<Waves/>} title="Connected" text="One view across sites, teams, and the subsurface."/></div></div></section>
    <section id="contact" className="mx-auto flex max-w-7xl flex-col justify-between gap-8 px-6 py-20 md:flex-row md:items-end lg:px-10"><div><p className="font-mono text-xs uppercase tracking-[.25em] text-primary">Contact operations</p><h2 className="mt-4 text-3xl font-semibold">Bring the ground into view.</h2><p className="mt-3 text-muted-foreground">Talk to the team about connecting your operation.</p></div><a href="mailto:operations@mokambo.example" className="flex items-center gap-3 border border-border px-5 py-3 text-sm hover:border-primary hover:text-primary"><Mail size={17}/> operations@mokambo.example</a></section>
    <footer className="border-t border-border px-6 py-6 lg:px-10"><div className="mx-auto flex max-w-7xl justify-between font-mono text-[10px] uppercase tracking-[.2em] text-muted-foreground"><span>© 2026 Mokambo Operations</span><span>Built for the field</span></div></footer>
  </main>
}
function Feature({icon,title,text}:{icon:React.ReactNode,title:string,text:string}) { return <div className="flex gap-4 border border-border bg-card/60 p-5"><span className="text-primary">{icon}</span><div><h3 className="font-medium">{title}</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">{text}</p></div></div> }
